"""
BriefBot — AI Sales Briefing Agent
Powered by Locus (beta.paywithlocus.com)
"""

import logging
from datetime import datetime, timezone
from pathlib import Path

from fastapi import FastAPI, BackgroundTasks, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel

import markdown as md_lib

from config import SERVER_URL, TIER_CONFIG, AGENTMAIL_INBOX_ID
from database import init_db, create_order, get_order, get_all_orders, get_dashboard_stats, update_order
from locus_client import LocusClient
from pipeline import run_pipeline

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s %(message)s")
log = logging.getLogger("briefbot")

app = FastAPI(title="BriefBot", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

FRONTEND = Path(__file__).resolve().parent.parent / "frontend"


@app.on_event("startup")
def on_startup():
    init_db()


# ────────────────────────── API ──────────────────────────


class OrderIn(BaseModel):
    company_name: str
    company_domain: str = ""
    context: str = ""
    client_email: str
    tier: str = "pro"


@app.post("/api/orders")
async def api_create_order(body: OrderIn):
    tier = body.tier if body.tier in TIER_CONFIG else "pro"
    price = TIER_CONFIG[tier]["price"]

    oid = create_order(
        body.company_name,
        body.company_domain.strip().lower(),
        body.context,
        body.client_email,
        price,
        tier,
    )
    locus = LocusClient()
    tier_label = TIER_CONFIG[tier]["label"]
    session = await locus.create_checkout_session(
        amount=str(price),
        description=f"BriefBot {tier_label} Briefing — {body.company_name}",
        success_url=f"{SERVER_URL}/report/{oid}",
        cancel_url=f"{SERVER_URL}/",
        order_id=oid,
    )
    if not session.get("success"):
        update_order(oid, status="FAILED", error="Failed to create payment session")
        raise HTTPException(500, "Could not create payment session")

    checkout_url = session["data"]["checkoutUrl"]
    checkout_session_id = session["data"]["id"]
    update_order(oid, checkout_session_id=checkout_session_id)

    return {"order_id": oid, "price": price, "tier": tier, "checkout_url": checkout_url}


@app.get("/api/orders/{oid}")
async def api_get_order(oid: str, bg: BackgroundTasks):
    order = get_order(oid)
    if not order:
        raise HTTPException(404, "Order not found")

    # Check Locus for payment confirmation
    if order["status"] == "AWAITING_PAYMENT" and order.get("checkout_session_id"):
        try:
            locus = LocusClient()
            session = await locus.get_checkout_session(order["checkout_session_id"])
            if session.get("success") and session["data"]["status"] == "PAID":
                now = datetime.now(timezone.utc).isoformat()
                update_order(oid, status="PROCESSING", paid_at=now)
                order["status"] = "PROCESSING"
                order["paid_at"] = now
                bg.add_task(
                    run_pipeline, oid, order["company_name"],
                    order["company_domain"], order["context"],
                    order.get("tier", "pro")
                )
        except Exception as e:
            log.warning("Payment check failed for %s: %s", oid, e)

    return order


@app.post("/api/orders/{oid}/send-email")
async def api_send_email(oid: str):
    order = get_order(oid)
    if not order:
        raise HTTPException(404, "Order not found")
    if order["status"] != "COMPLETED":
        raise HTTPException(400, "Report not ready yet")
    if not AGENTMAIL_INBOX_ID:
        raise HTTPException(503, "Email delivery not configured")

    tier_label = TIER_CONFIG.get(order.get("tier", "pro"), {}).get("label", "Pro")
    subject = f"Your BriefBot {tier_label} Report — {order['company_name']}"

    # Convert markdown → HTML for a nice email
    report_html = md_lib.markdown(order["report"], extensions=["tables"])
    body = f"""<html><body style="font-family:sans-serif;max-width:700px;margin:auto;color:#1e293b">
<h2 style="color:#4f46e5">BriefBot {tier_label} Sales Briefing</h2>
<p><strong>Company:</strong> {order['company_name']} &nbsp;|&nbsp;
   <strong>Domain:</strong> {order['company_domain'] or '—'}</p>
<hr style="border:none;border-top:1px solid #e2e8f0;margin:16px 0"/>
{report_html}
<hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0"/>
<p style="font-size:12px;color:#94a3b8">
  Generated by <a href="https://briefbot.ai" style="color:#6366f1">BriefBot</a> —
  powered by <a href="https://beta.paywithlocus.com" style="color:#6366f1">Locus</a>
</p>
</body></html>"""

    try:
        locus = LocusClient()
        result = await locus.send_email(
            inbox_id=AGENTMAIL_INBOX_ID,
            to_email=order["client_email"],
            subject=subject,
            body=body,
        )
        if not result.get("success"):
            raise HTTPException(500, result.get("message", "Email send failed"))
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(500, str(e))

    return {"sent": True, "to": order["client_email"]}


@app.get("/api/orders")
async def api_list_orders():
    return get_all_orders()


@app.get("/api/dashboard")
async def api_dashboard():
    stats = get_dashboard_stats()
    try:
        locus = LocusClient()
        bal = await locus.get_balance()
        stats["wallet_balance"] = bal.get("data", {}).get("usdc_balance", "0.00")
        stats["wallet_address"] = bal.get("data", {}).get("wallet_address", "")
    except Exception:
        stats["wallet_balance"] = "N/A"
        stats["wallet_address"] = ""
    stats["report_price"] = TIER_CONFIG["pro"]["price"]
    stats["tiers"] = TIER_CONFIG
    return stats


# ────────────────────────── Frontend ──────────────────────────


app.mount("/static", StaticFiles(directory=str(FRONTEND)), name="static")


@app.get("/")
async def page_index():
    return FileResponse(FRONTEND / "index.html")


@app.get("/report/{oid}")
async def page_report(oid: str):
    return FileResponse(FRONTEND / "report.html")


@app.get("/dashboard")
async def page_dashboard():
    return FileResponse(FRONTEND / "dashboard.html")
